source 'http://rubygems.org'

gem 'rails', '3.1.2'
gem 'pg'
gem 'unicorn'
gem 'haml'
gem 'haml-rails'
gem 'amqp'
gem 'net-ldap'
gem 'ipaddress', '0.8.0'
gem 'jquery-rails'
gem 'netaddr'
gem 'treetop'
gem 'carrot'
gem 'capistrano'
gem 'execjs'
gem 'therubyracer'
 
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'rails-erd'
  gem 'capistrano'
end

group :test do
  gem 'turn', :require => false
end
